#!/bin/sh

checkip() {
  curl -G https://api.abuseipdb.com/api/v2/check \
    --data-urlencode "ipAddress=$1" \
    -H "Key: $ABUSEIPDB_KEY" \
    -H "Accept: application/json" 2>/dev/null | jq .
}

rssh_top() {
  N=${1:-3}
  cat - | grep '"msg":"accepted"' | jq -r '.raddr.IP' | sort | uniq -c | sort -rn | head -$N
}

rssh_top_report() {
  rssh_top $1 | while IFS= read -r line; do
      L=$(echo $line | xargs echo)
      COUNT=$(echo $L | cut -d' ' -f1)
      IP=$(echo $L | cut -d' ' -f2)
      checkip "$(echo $IP)" | jq ". + {requests: $COUNT}"
  done
}